WORDS_AND_CLUES = [
    ("médico", "turno de noche"),
    ("enfermera", "carrito de medicinas"),
    ("profesor", "pizarra llena"),
    ("alumno", "examen sorpresa"),
    ("chef", "olla hirviendo"),
    ("camarero", "mesa para cuatro"),
    ("policía", "patrulla nocturna"),
    ("bombero", "alarma temprano"),
    ("mecánico", "manchas de aceite"),
    ("taxista", "radio encendida"),
    ("piloto", "vuelo retrasado"),
    ("azafata", "carrito de bebidas"),
    ("actor", "ensayo interrumpido"),
    ("director", "guión subrayado"),
    ("periodista", "entrevista cancelada"),
    ("fotógrafo", "cámara sin batería"),
    ("músico", "acorde desafinado"),
    ("cantante", "voz ronca"),
    ("diseñador", "pantalla azul"),
    ("programador", "código que no compila"),
    ("arquitecto", "maqueta terminada"),
    ("ingeniero", "cálculo repetido"),
    ("abogado", "audiencia prolongada"),
    ("juez", "sentencia leída"),
    ("psicólogo", "silencio incómodo"),
    ("dentista", "cita a las ocho"),
    ("veterinario", "perro nervioso"),
    ("panadero", "horno a las cinco"),
    ("carnicero", "cuchillo afilado"),
    ("pescadero", "hielo derretido"),
    ("florista", "rosas para una boda"),
    ("cartero", "carta certificada"),
    ("agricultor", "lluvia esperada"),
    ("pescador", "anzuelo vacío"),
    ("piloto de barco", "niebla en el mar"),
    ("soldado", "orden recibida"),
    ("espía", "coche estacionado"),
    ("detective", "foto desenfocada"),
    ("ladrón", "calle oscura"),
    ("vecino", "música alta"),
    ("novio", "cita a ciegas"),
    ("ex", "llamada a medianoche"),
    ("jefe", "reunión de urgencia"),
    ("suegra", "pastel quemado"),
    ("hermano", "llave prestada"),
    ("hijo", "deberes incompletos"),
    ("padre", "coche averiado"),
    ("madre", "sopa fría"),
    ("abuelo", "reloj antiguo"),
    ("abuela", "receta de galletas"),
    ("tío", "historia repetida"),
    ("tía", "abrigo de invierno"),
    ("primo", "juego de cartas"),
    ("amigo", "mensaje sin responder"),
    ("rival", "mirada cruzada"),
    ("compañero", "café compartido"),
    ("entrenador", "silbato roto"),
    ("deportista", "lesión antigua"),
    ("youtuber", "grabación interrumpida"),
    ("influencer", "foto sin filtro"),
    ("blogger", "entrada pendiente"),
    ("podcaster", "micrófono apagado"),
    ("locutor", "comercial sorpresa"),
    ("presentador", "teleprompter vacío"),
    ("editor", "plazo vencido"),
    ("traductor", "palabra ambigua"),
    ("intérprete", "acento marcado"),
    ("lingüista", "lenguaje muerto"),
    ("historiador", "archivo cerrado"),
    ("arqueólogo", "excavación sellada"),
    ("geólogo", "roca inusual"),
    ("astrónomo", "estrella fugaz"),
    ("biólogo", "jaula abierta"),
    ("químico", "frasco sin etiqueta"),
    ("físico", "ecuación incompleta"),
    ("matemático", "número irracional"),
    ("filósofo", "pregunta sin respuesta"),
    ("poeta", "verso incompleto"),
    ("escritor", "bloqueo creativo"),
    ("novelista", "final alternativo"),
    ("dramaturgo", "escena cortada"),
    ("bailarín", "zapato roto"),
    ("pintor", "lienzo en blanco"),
    ("escultor", "mármol sin tallar"),
    ("fotógrafo de bodas", "novia nerviosa"),
    ("dj", "vinilo rayado"),
    ("barman", "cóctel experimental"),
    ("recepcionista", "llamada perdida"),
    ("secretaria", "agenda llena"),
    ("administrativo", "impresora atascada"),
    ("contador", "declaración tardía"),
    ("auditor", "libro sin firmar"),
    ("consultor", "informe extenso"),
    ("vendedor", "cliente indeciso"),
    ("comercial", "oferta irrepetible"),
    ("repartidor", "paquete equivocado"),
    ("mensajero", "dirección incorrecta"),
    ("limpiador", "habitación vacía"),
    ("guardia", "ronda nocturna"),
    ("vigilante", "sensor activado"),
    ("portero", "llave maestra"),
    ("jardinero", "planta marchita"),
    ("albañil", "pared torcida"),
    ("electricista", "fusible quemado"),
    ("fontanero", "fuga en el techo"),
    ("cuidador", "receta vencida"),
    ("auxiliar", "carrito lleno"),
    ("bibliotecario", "libro extraviado"),
    ("archivero", "caja desordenada"),
    ("mensajero judicial", "notificación urgente"),
    ("reclutador", "entrevista fallida"),
    ("coach", "sesión cancelada"),
    ("terapeuta", "cita reprogramada"),
    ("nutricionista", "dieta equilibrada"),
    ("fisioterapeuta", "músculo contracturado"),
    ("masajista", "aceite tibio"),
    ("astronauta", "gravedad cero"),
    ("cosmonauta", "señal perdida"),
    ("explorador", "mapa rasgado"),
    ("aventurero", "brújula defectuosa"),
    ("pirata", "brújula girando"),
    ("corsario", "botín escondido"),
    ("ninja", "sombra silenciosa"),
    ("samurái", "espada desenvainada"),
    ("caballero", "escudo agrietado"),
    ("dragón", "cueva humeante"),
    ("hechicero", "pergamino enrollado"),
    ("bruja", "caldero humeante"),
    ("duende", "moneda brillante"),
    ("hada", "polvo brillante"),
    ("vampiro", "ataúd abierto"),
    ("zombi", "cerebro intacto"),
    ("fantasma", "eco en la sala"),
    ("extraterrestre", "nave invisible"),
    ("robot", "código errático"),
    ("clon", "ADN idéntico"),
    ("mutante", "rasgo inusual"),
    ("superhéroe", "disfraz arrugado"),
    ("villano", "plan incompleto"),
    ("detective privado", "sobre lacrado"),
    ("informante", "nota anónima"),
    ("fugitivo", "tren en marcha"),
    ("refugiado", "maleta ligera"),
    ("inmigrante", "frontera abierta"),
    ("diplomático", "carta sellada"),
    ("embajador", "bandera descolorida"),
    ("intérprete de conferencias", "auricular defectuoso"),
    ("traductor jurado", "sello oficial"),
    ("intérprete de signos", "manos rápidas"),
    ("cuidador de niños", "cuna meciéndose"),
    ("canguro", "dibujo en la pared"),
    ("niñera", "cuento interrumpido"),
    ("tutor", "ejercicio resuelto"),
    ("orientador", "carrera incierta"),
    ("psiquiatra", "diagnóstico abierto"),
    ("neurólogo", "reflejo lento"),
    ("cardiólogo", "ritmo irregular"),
    ("oncólogo", "prueba pendiente"),
    ("pediatra", "vacuna programada"),
    ("ginecólogo", "ecografía borrosa"),
    ("dermatólogo", "lunar sospechoso"),
    ("oftalmólogo", "visión borrosa"),
    ("otorrino", "audífono antiguo"),
    ("urólogo", "análisis en camino"),
    ("traumatólogo", "yeso recién puesto"),
    ("anestesista", "monitor activo"),
    ("radiólogo", "placa expuesta"),
    ("patólogo", "muestra etiquetada"),
    ("toxicólogo", "antídoto listo"),
    ("epidemiólogo", "muestra en cuarentena"),
    ("microbiólogo", "cultivo creciendo"),
    ("genetista", "secuencia incompleta"),
    ("bioético", "dilema moral"),
    ("crítico de cine", "reseña escrita"),
    ("crítico de teatro", "telón bajado"),
    ("crítico de arte", "obra polémica"),
    ("crítico literario", "final discutido"),
    ("crítico musical", "nota discordante"),
    ("comisario de exposición", "sala vacía"),
    ("curador", "obra restaurada"),
    ("coleccionista", "pieza única"),
    ("anticuario", "mueble antiguo"),
    ("subastador", "martillo levantado"),
    ("marchante", "galería cerrada"),
    ("crítico gastronómico", "plato frío"),
    ("catador", "copa medio vacía"),
    ("sumiller", "botella sellada"),
    ("panadero artesano", "masa fermentando"),
    ("cervecero", "barril lleno"),
    ("vinatero", "bodega oscura"),
    ("agricultor ecológico", "semilla certificada"),
    ("ganadero", "rebaño disperso"),
    ("apicultor", "colmena activa"),
    ("pescador artesanal", "red reparada"),
    ("cazador", "rastro fresco"),
    ("guardabosques", "sendero marcado"),
    ("guía turístico", "grupo perdido"),
    ("traductor simultáneo", "cabina llena"),
    ("intérprete médico", "historial incompleto"),
    ("coordinador", "reunión aplazada"),
    ("supervisor", "informe semanal"),
    ("director de orquesta", "batuta en alto"),
    ("maestro de ceremonias", "micrófono apagado"),
    ("animador", "fiesta silenciosa"),
    ("presentador de radio", "canción cortada"),
    ("locutor deportivo", "gol anulado"),
    ("comentarista", "opinión polarizada"),
    ("analista político", "encuesta reciente"),
    ("columnista", "plazo ajustado"),
    ("redactor", "titular cambiado"),
    ("corrector", "tilde olvidada"),
    ("tipógrafo", "fuente antigua"),
    ("ilustrador", "boceto inicial"),
    ("diseñador gráfico", "paleta de colores"),
    ("diseñador web", "página en construcción"),
    ("desarrollador frontend", "botón invisible"),
    ("desarrollador backend", "base de datos lenta"),
    ("devops", "servidor caído"),
    ("analista de datos", "gráfico erróneo"),
    ("científico de datos", "modelo entrenado"),
    ("ingeniero de ML", "red neuronal"),
    ("arquitecto de software", "diagrama complejo"),
    ("tester", "error no reproducible"),
    ("scrum master", "sprint terminado"),
    ("product owner", "backlog priorizado"),
    ("gerente de proyecto", "entrega retrasada"),
    ("director de marketing", "campaña finalizada"),
    ("estratega", "plan en marcha"),
    ("community manager", "comentario eliminado"),
    ("especialista en SEO", "palabra clave"),
    ("analista de redes", "seguidor falso"),
    ("creador de contenido", "idea descartada"),
    ("guionista", "diálogo reescrito"),
    ("storyboarder", "viñeta vacía"),
    ("director de arte", "paleta elegida"),
    ("fotógrafo de moda", "ropa arrugada"),
    ("maquillador", "brocha sucia"),
    ("peluquero", "tijeras afiladas"),
    ("modisto", "telar antiguo"),
    ("diseñador de interiores", "sofá incómodo"),
    ("decorador", "pintura fresca"),
    ("florista de eventos", "centro de mesa"),
    ("organizador de bodas", "lista de invitados"),
    ("planificador de eventos", "catering confirmado"),
    ("logístico", "camión retrasado"),
]