# impostor_words.py — 250 pares probados para máxima diversión
WORDS_AND_CLUES = [
    ("asesino", "coartada"),
    ("médico", "receta falsa"),
    ("abogado", "sobre lacrado"),
    ("diputado", "maletín sin declarar"),
    ("profesor", "examen filtrado"),
    ("novio", "mensaje borrado"),
    ("ex", "fotos en la nube"),
    ("jefe", "despido injusto"),
    ("suegra", "cena de Navidad"),
    ("hermano", "testamento alterado"),
    ("vecino", "cámara en el portal"),
    ("influencer", "cirugía no declarada"),
    ("youtuber", "clickbait mortal"),
    ("político", "promesa incumplida"),
    ("banquero", "deuda oculta"),
    ("pastor", "pecado confesado"),
    ("actor", "papel falso"),
    ("modelo", "filtro real"),
    ("periodista", "fuente anónima"),
    ("mafioso", "pescado en el maletero"),
    ("espía", "micrófono en el florero"),
    ("traidor", "grupo de WhatsApp"),
    ("ladrón", "huella en la copa"),
    ("gemelo malvado", "espejo roto"),
    ("niñera", "puerta cerrada con llave"),
    ("psicópata", "terapia"),
    ("cirujano", "instrumento olvidado"),
    ("enfermera", "inyección sospechosa"),
    ("farmacéutico", "pastilla experimental"),
    ("dentista", "radiografía falsa"),
    ("veterinario", "perro testigo"),
    ("piloto", "caja negra borrada"),
    ("mecánico", "freno saboteado"),
    ("taxista", "viaje sin registro"),
    ("camarero", "copa envenenada"),
    ("chef", "ingrediente prohibido"),
    ("panadero", "harina mágica"),
    ("carnicero", "cuchillo limpio"),
    ("pescadero", "red vacía"),
    ("florista", "rosa negra"),
    ("cartero", "carta no entregada"),
    ("bombero", "fuego provocado"),
    ("policía", "placa falsa"),
    ("detective", "foto borrosa"),
    ("guardia de seguridad", "cámara apagada"),
    ("soldado", "orden falsa"),
    ("espía industrial", "USB robado"),
    ("falsificador", "billete perfecto"),
    ("chantajista", "video íntimo"),
    ("secuestrador", "ransom en Bitcoin"),
    ("estafador", "herencia ficticia"),
    ("ladrón de guante blanco", "joya desaparecida"),
    ("informante", "llamada anónima"),
    ("delator", "correo cifrado"),
    ("cómplice", "coartada compartida"),
    ("encubridor", "testigo desaparecido"),
    ("fugitivo", "pasaporte falso"),
    ("hackeador", "contraseña maestra"),
    ("asesino a sueldo", "factura sin IVA"),
    ("conspirador", "teoría del ovni"),
    ("adicto", "último chute"),
    ("millonario", "paraíso fiscal"),
    ("fiscal", "caja fuerte vacía"),
    ("novia", "anillo de compromiso"),
    ("marido", "segunda boda"),
    ("hijo", "herencia anticipada"),
    ("tío rico", "testamento envenenado"),
    ("celebridad", "escándalo en la ducha"),
    ("gurú", "curso de 10.000€"),
    ("psiquiatra", "diagnóstico falso"),
    ("neurólogo", "amnesia inducida"),
    ("cardiólogo", "marcapasos desactivado"),
    ("oncólogo", "diagnóstico retrasado"),
    ("pediatra", "vacuna caducada"),
    ("ginecólogo", "ultrasonido falso"),
    ("dermatólogo", "crema mágica"),
    ("oftalmólogo", "lentes oscuras"),
    ("otorrino", "audífono espía"),
    ("urólogo", "análisis alterado"),
    ("traumatólogo", "yeso falso"),
    ("anestesista", "dosis extra"),
    ("radiólogo", "rayos X borrados"),
    ("patólogo", "autopsia incompleta"),
    ("toxicólogo", "antídoto perdido"),
    ("epidemiólogo", "virus liberado"),
    ("filósofo", "paradoja mortal"),
    ("poeta", "verso envenenado"),
    ("escritor", "manuscrito robado"),
    ("editor", "libro censurado"),
    ("crítico", "reseña falsa"),
    ("traductor", "mensaje alterado"),
    ("intérprete", "conversación secreta"),
    ("lingüista", "código indescifrable"),
    ("historiador del arte", "cuadro falso"),
    ("crítico de cine", "reseña comprada"),
    ("director", "escena cortada"),
    ("productor", "presupuesto inflado"),
    ("guionista", "final alternativo"),
    ("fotógrafo", "foto retocada"),
    ("diseñador", "logo robado"),
    ("arquitecto", "plano defectuoso"),
    ("ingeniero", "puente colapsado"),
    ("constructor", "cemento aguado"),
    ("electricista", "cable cortado"),
    ("fontanero", "tubería envenenada"),
    ("sastre", "traje con bolsillo secreto"),
    ("modisto", "vestido con veneno"),
    ("peluquero", "tinte alucinógeno"),
    ("maquillador", "máscara permanente"),
    ("perfumista", "fragancia hipnótica"),
    ("joyero", "diamante falso"),
    ("relojero", "hora detenida"),
    ("anticuario", "objeto maldito"),
    ("coleccionista", "pieza robada"),
    ("marchante", "obra falsa"),
    ("crítico de vino", "botella envenenada"),
    ("sommelier", "copa vacía"),
    ("chef de estrella", "ingrediente prohibido"),
    ("panadero artesano", "levadura secreta"),
    ("cervecero", "lote contaminado"),
    ("vinatero", "barrica encantada"),
    ("agricultor", "plaga deliberada"),
    ("ganadero", "vaca loca"),
    ("pescador", "red con cuerpo"),
    ("cazador", "trofeo humano"),
    ("guardabosques", "trampa activada"),
    ("explorador", "mapa falso"),
    ("aventurero", "tesoro maldito"),
    ("pirata", "brújula rota"),
    ("corsario", "botín hundido"),
    ("bucanero", "isla abandonada"),
    ("navegante", "rumbo equivocado"),
    ("capitán", "barco fantasma"),
    ("grumete", "diario quemado"),
    ("cocinero de barco", "sopa de rata"),
    ("médico de a bordo", "amputación innecesaria"),
    ("marinero", "nudo corredizo"),
    ("ballenero", "arpon oxidado"),
    ("submarinista", "tanque vacío"),
    ("buceador", "tesoro maldito"),
    ("salvavidas", "rescate fallido"),
    ("surfista", "tiburón domesticado"),
    ("guardacostas", "barco ignorado"),
    ("contrabandista marítimo", "carga hundida"),
    ("traficante de arte", "cuadro robado"),
    ("vendedor de armas", "licencia falsa"),
    ("pirata informático", "clave maestra"),
    ("hacker ético", "prueba no autorizada"),
    ("desarrollador", "bug mortal"),
    ("programador", "código backdoor"),
    ("ingeniero de software", "actualización dañina"),
    ("administrador", "contraseña maestra"),
    ("analista", "dato manipulado"),
    ("científico de datos", "algoritmo sesgado"),
    ("IA", "prompt peligroso"),
    ("robot", "código corrompido"),
    ("clon", "ADN alterado"),
    ("mutante", "rayos gamma"),
    ("superhéroe", "identidad secreta"),
    ("villano", "plan maestro"),
    ("justiciero", "máscara quemada"),
    ("vengador", "lista de nombres"),
    ("asesino en serie", "trofeo guardado"),
    ("psicólogo", "fobia inventada"),
    ("astrónomo", "señal alienígena"),
    ("químico", "fórmula secreta"),
    ("biólogo", "experimento prohibido"),
    ("físico", "agujero negro en garaje"),
    ("matemático", "número de la suerte"),
    ("historiador", "manuscrito perdido"),
    ("arqueólogo", "maldición faraónica"),
    ("geólogo", "mina clandestina"),
    ("papá Noel", "lista negra"),
    ("san valentín", "rosas marchitas"),
    ("brujero", "muñeco con alfileres"),
    ("demonio", "pacto firmado"),
    ("ángel caído", "alas quemadas"),
    ("zombi", "cerebro frito"),
    ("vampiro", "banco de sangre"),
    ("extraterrestre", "abducción fallida"),
    ("dragón", "tesoro maldito"),
    ("hechicero", "poción del olvido"),
    ("bruja", "caldero burbujeante"),
    ("duende", "oro falso"),
    ("hada", "polvo alucinógeno"),
    ("ogro", "puente sin peaje"),
    ("cíclope", "ojo vendado"),
    ("minotauro", "laberinto vacío"),
    ("centauro", "flecha perdida"),
    ("sirena", "canto prohibido"),
    ("kraken", "barco hundido"),
    ("lobo", "aullido silenciado"),
    ("chupacabras", "cabras desangradas"),
    ("bigfoot", "huella borrosa"),
    ("alienígena", "implante cerebral"),
    ("robot domesticado", "orden mal interpretada"),
    ("asistente virtual", "grabación filtrada"),
    ("dron", "cámara espía"),
    ("satélite", "señal interceptada"),
    ("telescopio", "imagen falsa"),
    ("microscopio", "muestra contaminada"),
    ("laboratorio", "experimento prohibido"),
    ("clínica", "ficha alterada"),
    ("hospital", "médico desaparecido"),
    ("ambulancia", "ruta desviada"),
    ("funeraria", "ataúd vacío"),
    ("cementerio", "tumba falsa"),
    ("crematorio", "cenizas mezcladas"),
    ("tanatorio", "lágrima falsa"),
    ("viudo", "seguro de vida"),
    ("viuda", "herencia anticipada"),
    ("huérfano", "testamento perdido"),
    ("heredero", "asesinato conveniente"),
    ("testigo protegido", "identidad robada"),
    ("agente encubierto", "misión fallida"),
    ("informante policial", "pago no recibido"),
    ("delincuente", "coartada falsa"),
    ("reincidente", "huella coincidente"),
    ("preso", "túnel incompleto"),
    ("fugado", "muro escalado"),
    ("condenado", "sentencia revisada"),
    ("absuelto", "prueba destruida"),
    ("acusado", "testigo falso"),
    ("demandante", "demanda fraudulenta"),
    ("demandado", "prueba oculta"),
    ("juez", "soborno aceptado"),
    ("fiscal", "acusación falsa"),
    ("defensor", "prueba ocultada"),
    ("perito", "informe adulterado"),
    ("jurado", "voto comprado"),
    ("notario", "escritura falsa"),
    ("asesor legal", "consejo letal"),
    ("consultor", "informe sesgado"),
    ("auditor", "cuenta oculta"),
    ("contable", "factura doble"),
    ("economista", "predicción falsa"),
    ("banquero suizo", "cuenta secreta"),
    ("inversor", "acciones manipuladas"),
    ("trader", "orden ilegal"),
    ("agente inmobiliario", "casa embrujada"),
    ("arrendador", "alquiler negro"),
    ("inquilino", "depósito retenido"),
    ("desahuciado", "llave cambiada"),
    ("okupa", "puerta forzada"),
    ("empresario", "quiebra simulada"),
    ("emprendedor", "startup fantasma"),
    ("inversor ángel", "participación mayoritaria"),
    ("socio", "acuerdo verbal"),
    ("cofundador", "idea robada"),
    ("CEO", "despido masivo"),
    ("director general", "bonus oculto"),
    ("jefe de personal", "ficha alterada"),
    ("recursos humanos", "despido injusto"),
    ("departamento legal", "cláusula oculta"),
    ("departamento financiero", "fraude interno"),
    ("contabilidad", "libro mayor falsificado"),
    ("compliance", "norma violada"),
    ("seguridad", "cámara apagada"),
    ("IT", "acceso no autorizado"),
    ("marketing", "campaña engañosa"),
    ("publicidad", "mensaje subliminal"),
    ("relaciones públicas", "escándalo oculto"),
    ("comunicación", "rueda de prensa cancelada"),
    ("coach", "sesión privada"),
    ("terapeuta", "sesión grabada"),
    ("gurú espiritual", "retiro en la montaña"),
    ("monje", "manuscrito prohibido"),
    ("sacerdote", "confesionario roto"),
    ("obispo", "escándalo vaticano"),
    ("papa", "anillo desaparecido"),
    ("rey", "corona falsa"),
    ("emperador", "ejército secreto"),
    ("dictador", "discurso censurado"),
    ("primera dama", "joyas robadas"),
    ("príncipe", "boda anulada"),
    ("princesa", "vestido envenenado"),
    ("duque", "tierras usurpadas"),
    ("conde", "castillo embrujado"),
    ("barón", "mina de oro"),
    ("caballero", "espada oxidada"),
]